---
title: "p8105_hw5_yz4184"
author: "Yunlin Zhou"
date: "11/20/2021"
output: github_document
---

```{r echo = FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


### Problem 1

```{r}
homicide_df = 
  read_csv("./homicide-data.csv", na = c("","Unknown"))%>%
  mutate(
    city_state = str_c(city, state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved",
    )
  )%>%
  relocate(city_state)%>%
  filter(city_state != "TulsaAL")
```

```{r}

baltimore_df = 
  homicide_df%>%
  filter(city_state == "BaltimoreMD")

baltimore_summary = 
  baltimore_df%>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

baltimore_test =   
prop.test(
  x = baltimore_summary%>%pull(unsolved),
  n = baltimore_summary%>%pull(n))

baltimore_test%>%
  broom::tidy()
  
```

```{r}
prop_test_function = function(city_df){
  
  city_summary = 
  city_df%>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )
  
  
city_test =   
prop.test(
  x = city_summary%>%pull(unsolved),
  n = city_summary%>%pull(n))
  
return(city_test)
}

prop_test_function(baltimore_df)

homicide_df %>%
  filter(city_state == "AlbuquerqueNM")%>%
  prop_test_function()
```

```{r}
results_df = 
homicide_df%>%
  nest(data = uid:resolution)%>%
  mutate(
    test_results = map(data,prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  )%>%
  select(city_state, tidy_results)%>%
  unnest(tidy_results)%>%
  select(city_state, estimate, starts_with("conf"))

```

```{r}
results_df%>%
  mutate(
    city_state = fct_reorder(city_state, estimate))%>%
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point()+
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high))
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

```{r}
homicide_df%>%
group_by(city_state)%>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )%>%
  mutate(
    test_results = map2(unsolved,n,prop.test),
    tidy_results = map(test_results, broom::tidy)
  )%>%
  select(city_state, tidy_results)%>%
  unnest(tidy_results)%>%
  select(city_state, estimate, starts_with("conf"))
```


### Problem 2

```{r}
file_names = list.files(path = "./data")
```


```{r}
import_data = function(x){
  x = read_csv(x)
  return(x)
}

output =  map(file_names, import_data)

arms_df = bind_rows(output)%>%
  mutate(file_names)%>%
  nest(week_change = week_1 :week_8)
```


```{r}
library(stringr)

arms_df2 = arms_df%>%
  unnest(week_change)%>%
  separate(file_names, into = c("type", "id"), sep = "_")%>%
  mutate(type = str_replace(type, "con", "control_arm"),
         type = str_replace(type, "exp", "experimental_arm"),
         id = gsub(".csv","", x=id))%>%
  pivot_longer(
    week_1:week_8,
    names_to = "week", 
    values_to = "score")%>%
  mutate(week = sub("week_","", week),
         week = as.numeric(week))

ggplot(arms_df2, aes(x = week, y = score, color = id)) + 
  geom_line() + 
  facet_grid(. ~ type)

```

The data in control_arm group  changed over the time but it is approximately stable. The data in experimental_arm group has a obvious increasing trend. Also, it seems that the mean in control_arm group is smaller than that in experimental_arm group.

### Problem 3

```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

```

```{r}
fill_iris_missing = function(vector){
  if(is.numeric(vector)){
    vector= replace_na(vector, mean(vector, na.rm = TRUE))
  }
  if(is.character(vector)){
    vector= replace_na(vector, "virginica")
  }
  return(vector)
}

map(iris_with_missing, fill_iris_missing)
```

